#!/usr/bin/env bash
# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Set default to deny all incoming traffic
sudo ufw default deny incoming

# Set default to allow all outgoing traffic
sudo ufw default allow outgoing

# Allow SSH (port 22/tcp)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443/tcp)
sudo ufw allow 443/tcp

# Allow HTTP (port 80/tcp)
sudo ufw allow 80/tcp

# Enable ufw (--force skips the interactive prompt)
sudo ufw enable